### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timabell** [chriskenis/POSH#1]
Any chance of adding a permissive license for this repo assuming you have the rights to all the code in it?

Currently it's not legal for anyone else to use.

* https://help.github.com/articles/licensing-a-repository/
* https://help.github.com/articles/adding-a-license-to-a-repository/
* https://choosealicense.com/
* https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by timabell** [comment]
Background: I'd like to use it in my boxstarter script - https://gist.github.com/timabell/608fb680bfc920f372ac

**Comment by ChristelVDH** [comment]
thanks for pointing this out, sharing was always my intention and now it is official :)
